export const enum InteractiveConst {
  /** 无限盘子源 */
  PlateSource = 'PlateSource',
  /** 无限番茄源 */
  TomatoSource = 'TomatoSource',
  /** 无限面包源 */
  BreadSource = 'BreadSource',
  /** 无限生牛肉源 */
  BeefSource = 'BeefSource',
  /** 无限生菜源 */
  LettuceSource = 'LettuceSource',
  /** 刀板1 */
  CuttingBoard1 = 'CuttingBoard1',
  /** 刀板2 */
  CuttingBoard2 = 'CuttingBoard2',
  /** 刀板3 */
  CuttingBoard3 = 'CuttingBoard3',
  /** 刀板4 */
  CuttingBoard4 = 'CuttingBoard4',
  /** 刀板5 */
  CuttingBoard5 = 'CuttingBoard5',
  /** 煎锅1 */
  FryStove1 = 'FryStove1',
  /** 煎锅2 */
  FryStove2 = 'FryStove2',
  /** 锅炉1 */
  BoilStove1 = 'BoilStove1',
  /** 锅炉2 */
  BoilStove2 = 'BoilStove2',
  /** 垃圾桶 */
  Dustbin = 'Dustbin',
}
