export const enum SERVICE_TOKENS {
  PLAYER_SERVICE = 'PLAYER_SERVICE',
  DATA_SERVICE = 'DATA_SERVICE',
  ANIMATION_SERVICE = 'ANIMATION_SERVICE',
  COMMUNICATION_SERVICE = 'COMMUNICATION_SERVICE',
  SCORE_SERVICE = 'SCORE_SERVICE',
  ORDER_SERVICE = 'ORDER_SERVICE',
}
